#!/bin/bash

set -e

case $1 in
  chrome) browser="Chrome" ;;
  safari) browser="Safari" ;;
  firefox) browser="Firefox" ;;
  nightmare) browser="Nightmare" ;;
  all) browser="Chrome,Safari,Firefox,Nightmare" ;;
  # *) browser=$1 ;;
esac

if [[ $BROWSER_STACK_ENV ]] || [[ $1 == browserstack:* ]]; then
  browser="$1"
fi

if [ ! $browser ]; then

  export NODE_ENV=test
  ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- \
  $@ \
  test/unit/*.js \
  sources/**/*.spec.js

  if [ ! -z "$EXPORT_COVERAGE" ]; then
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    rm -rf ./coverage
  fi

else

  ./node_modules/.bin/karma start karma.config.js --browsers $browser $@

fi
